{
    "dataSources":[
       {
          "xid":"DS_943244",
          "type":"MODBUS_IP",
          "alarmLevels":{
             "POINT_WRITE_EXCEPTION":"URGENT",
             "DATA_SOURCE_EXCEPTION":"URGENT",
             "POINT_READ_EXCEPTION":"URGENT"
          },
          "updatePeriodType":"SECONDS",
          "transportType":"TCP",
          "contiguousBatches":false,
          "createSlaveMonitorPoints":false,
          "createSocketMonitorPoint":false,
          "enabled":true,
          "encapsulated":false,
          "host":"192.25.0.8",
          "maxReadBitCount":2000,
          "maxReadRegisterCount":125,
          "maxWriteRegisterCount":120,
          "name":"OpenPLC",
          "port":502,
          "quantize":false,
          "retries":2,
          "timeout":500,
          "updatePeriods":5
       }
    ],
    "dataPoints":[
       {
          "xid":"DP_977077",
          "loggingType":"ON_CHANGE",
          "intervalLoggingPeriodType":"MINUTES",
          "intervalLoggingType":"INSTANT",
          "purgeType":"YEARS",
          "pointLocator":{
             "range":"INPUT_REGISTER",
             "modbusDataType":"TWO_BYTE_INT_UNSIGNED",
             "additive":0.0,
             "bit":0,
             "charset":"ASCII",
             "multiplier":1.0,
             "offset":100,
             "registerCount":0,
             "settableOverride":true,
             "slaveId":1,
             "slaveMonitor":false,
             "socketMonitor":false
          },
          "eventDetectors":[
          ],
          "engineeringUnits":"",
          "purgeStrategy":"PERIOD",
          "chartColour":null,
          "chartRenderer":null,
          "dataSourceXid":"DS_943244",
          "defaultCacheSize":1,
          "description":"",
          "deviceName":"OpenPLC - Level",
          "discardExtremeValues":false,
          "discardHighLimit":1.7976931348623157E308,
          "discardLowLimit":-1.7976931348623157E308,
          "enabled":true,
          "eventTextRenderer":{
             "type":"EVENT_NONE"
          },
          "intervalLoggingPeriod":15,
          "name":"Level",
          "purgePeriod":1,
          "purgeValuesLimit":100,
          "textRenderer":{
             "type":"PLAIN",
             "suffix":""
          },
          "tolerance":0.0
       },
       {
          "xid":"DP_240011",
          "loggingType":"ON_CHANGE",
          "intervalLoggingPeriodType":"MINUTES",
          "intervalLoggingType":"INSTANT",
          "purgeType":"YEARS",
          "pointLocator":{
             "range":"INPUT_REGISTER",
             "modbusDataType":"TWO_BYTE_INT_UNSIGNED",
             "additive":0.0,
             "bit":0,
             "charset":"ASCII",
             "multiplier":1.0,
             "offset":101,
             "registerCount":0,
             "settableOverride":true,
             "slaveId":1,
             "slaveMonitor":false,
             "socketMonitor":false
          },
          "eventDetectors":[
          ],
          "engineeringUnits":"",
          "purgeStrategy":"PERIOD",
          "chartColour":null,
          "chartRenderer":null,
          "dataSourceXid":"DS_943244",
          "defaultCacheSize":1,
          "description":"",
          "deviceName":"OpenPLC - Q_In",
          "discardExtremeValues":false,
          "discardHighLimit":1.7976931348623157E308,
          "discardLowLimit":-1.7976931348623157E308,
          "enabled":true,
          "eventTextRenderer":{
             "type":"EVENT_NONE"
          },
          "intervalLoggingPeriod":15,
          "name":"Q_In",
          "purgePeriod":1,
          "purgeValuesLimit":100,
          "textRenderer":{
             "type":"PLAIN",
             "suffix":""
          },
          "tolerance":0.0
       },
       {
          "xid":"DP_514731",
          "loggingType":"ON_CHANGE",
          "intervalLoggingPeriodType":"MINUTES",
          "intervalLoggingType":"INSTANT",
          "purgeType":"YEARS",
          "pointLocator":{
             "range":"INPUT_REGISTER",
             "modbusDataType":"TWO_BYTE_INT_UNSIGNED",
             "additive":0.0,
             "bit":0,
             "charset":"ASCII",
             "multiplier":1.0,
             "offset":102,
             "registerCount":0,
             "settableOverride":true,
             "slaveId":1,
             "slaveMonitor":false,
             "socketMonitor":false
          },
          "eventDetectors":[
          ],
          "engineeringUnits":"",
          "purgeStrategy":"PERIOD",
          "chartColour":null,
          "chartRenderer":null,
          "dataSourceXid":"DS_943244",
          "defaultCacheSize":1,
          "description":"",
          "deviceName":"OpenPLC - Valve",
          "discardExtremeValues":false,
          "discardHighLimit":1.7976931348623157E308,
          "discardLowLimit":-1.7976931348623157E308,
          "enabled":true,
          "eventTextRenderer":{
             "type":"EVENT_NONE"
          },
          "intervalLoggingPeriod":15,
          "name":"Q_Out",
          "purgePeriod":1,
          "purgeValuesLimit":100,
          "textRenderer":{
             "type":"PLAIN",
             "suffix":""
          },
          "tolerance":0.0
       },
       {
          "xid":"DP_829729",
          "loggingType":"ON_CHANGE",
          "intervalLoggingPeriodType":"MINUTES",
          "intervalLoggingType":"INSTANT",
          "purgeType":"YEARS",
          "pointLocator":{
             "range":"INPUT_REGISTER",
             "modbusDataType":"TWO_BYTE_INT_UNSIGNED",
             "additive":0.0,
             "bit":0,
             "charset":"ASCII",
             "multiplier":1.0,
             "offset":103,
             "registerCount":0,
             "settableOverride":true,
             "slaveId":1,
             "slaveMonitor":false,
             "socketMonitor":false
          },
          "eventDetectors":[
          ],
          "engineeringUnits":"",
          "purgeStrategy":"PERIOD",
          "chartColour":null,
          "chartRenderer":null,
          "dataSourceXid":"DS_943244",
          "defaultCacheSize":1,
          "description":"missing deciment ",
          "deviceName":"OpenPLC - Temp",
          "discardExtremeValues":false,
          "discardHighLimit":1.7976931348623157E308,
          "discardLowLimit":-1.7976931348623157E308,
          "enabled":true,
          "eventTextRenderer":{
             "type":"EVENT_NONE"
          },
          "intervalLoggingPeriod":15,
          "name":"Temp",
          "purgePeriod":1,
          "purgeValuesLimit":100,
          "textRenderer":{
             "type":"PLAIN",
             "suffix":""
          },
          "tolerance":0.0
       },
       {
          "xid":"DP_458992",
          "loggingType":"ON_CHANGE",
          "intervalLoggingPeriodType":"MINUTES",
          "intervalLoggingType":"INSTANT",
          "purgeType":"YEARS",
          "pointLocator":{
             "range":"INPUT_REGISTER",
             "modbusDataType":"TWO_BYTE_INT_UNSIGNED",
             "additive":0.0,
             "bit":0,
             "charset":"ASCII",
             "multiplier":1.0,
             "offset":104,
             "registerCount":0,
             "settableOverride":true,
             "slaveId":1,
             "slaveMonitor":false,
             "socketMonitor":false
          },
          "eventDetectors":[
          ],
          "engineeringUnits":"",
          "purgeStrategy":"PERIOD",
          "chartColour":null,
          "chartRenderer":null,
          "dataSourceXid":"DS_943244",
          "defaultCacheSize":1,
          "description":"",
          "deviceName":"OpenPLC - Press",
          "discardExtremeValues":false,
          "discardHighLimit":1.7976931348623157E308,
          "discardLowLimit":-1.7976931348623157E308,
          "enabled":true,
          "eventTextRenderer":{
             "type":"EVENT_NONE"
          },
          "intervalLoggingPeriod":15,
          "name":"Press",
          "purgePeriod":1,
          "purgeValuesLimit":100,
          "textRenderer":{
             "type":"PLAIN",
             "suffix":""
          },
          "tolerance":0.0
       }
    ],
    "watchLists":[
       {
          "xid":"WL_762594",
          "user":"admin",
          "dataPoints":[
          ],
          "sharingUsers":[
          ],
          "name":"(unnamed)"
       },
       {
          "xid":"WL_325888",
          "user":"admin",
          "dataPoints":[
             "DP_977077",
             "DP_458992",
             "DP_240011",
             "DP_514731",
             "DP_829729"
          ],
          "sharingUsers":[
          ],
          "name":"Plant"
       }
    ]
 }